### ISSUE TITLE
Implement with trait instead of base class

### ISSUE THREAD

**Issue by Bilge** [amphp/phpunit-util#10]
It is common for PHPUnit extensions to implement functionality with base classes, but we can only extend one. Therefore, it is often impossible to use two or more extensions at once. For example, one may wish to use Symfony's `WebTestCase` but also `AsyncTestCase`, which is impossible since both must be extended directly.

Since traits offer unlimited extension, an alternative implementation should be offered in addition to/instead of the current base class approach.

**Comment by kelunik** [comment]
The behavior of this class makes it unlikely to work well with traits, I think. We might consider a PR for this, but I'm not really a fan of traits.
