### ISSUE TITLE
Loop runs forever

### ISSUE THREAD

**Issue by prolic** [amphp/phpunit-util#12]
I have a TCP connection running in the event loop. This TCP connection has always something to do, like handling heart beats. I need to explicitly close the connection, otherwise the loop will run forever and never stop.

I used `wait(call(...))` before and there wasn't this problem. Using phpunit-util, I need to close the connection manually and add that line of code more than 400 test cases. Is there a way around this that can be incorporated into this lib?

**Comment by trowski** [comment]
A combination of `TestCase::setup()` and `TestCase::tearDown()` can probably solve your issues without having to modify every test.

**Comment by prolic** [comment]
I tried that, but `tearDown()` never gets called, because the test hangs in the test-method itself, because the loop won't stop running.

**Comment by prolic** [comment]
Well, if there is nothing that can be done about it, I think I need to go and change a couple hundred of tests. Thanks anyway! You helped me again.

**Comment by trowski** [comment]
Hmm… yes, I didn't think about `tearDown()` not being reached.

An `afterResolve()` method could be added that is executed after the returned promise is resolved but before the loop exits.

**Comment by kelunik** [comment]
I guess the proper solution is to unreference the connection as long as it's idle, only doing heartbeats.

**Comment by prolic** [comment]
Should I reference back again when a new operation is executed and
unreference as soon as the operation is done?

**Comment by kelunik** [comment]
Yup.

**Comment by prolic** [comment]
Thanks, I'll give a try.
