### ISSUE TITLE
Mocking a class without a mocked method that would normally return a promise causes the loop to stop without resolving the test

### ISSUE THREAD

**Issue by Nessworthy** [amphp/phpunit-util#19]
For example:

```php
<?php

use Amp\PHPUnit\AsyncTestCase;
use Amp\Success;
use Generator;

class MockedClass {
    public function doSomething(): Promise {
        return new Success('Some Value');
    }
}

class TestedClass {

    private MockedClass $mockedClass;

    public function __construct(MockedClass $mockedClass) {
        $this->mockedClass = $mockedClass;
    }

    public function performAction(): Promise
    {
        // Not the greatest example..
        return new Success( yield $this->mockedClass->doSomething() );
    }
}

class TestedClassTest extends AsyncTestCase {
    public function testPerformAction() {
        $mockedClass = $this->createMock(MockedClass::CLASS);
        $testedClass = new TestedClass($mockedClass);

        yield $testedClass->performAction();

        $this->assertEquals(1, 1);  // Is never reached.
    }
}
```

Causes: `Loop stopped without resolving promise or coroutine returned from test method`

If you define the method mock which is yielded inside `TestedClass` to return a promise, it works.

Caused a fair bit of confusion writing tests, wouldn't mind an easier to understand error message if possible!

**Comment by remorhaz** [comment]
I've noticed this problem, too, but I don't have any idea of how it could be solved. The auto-mocked promise is never resolved for obvious reasons; the desired behavior would be probably to auto-return Amp\Success(<auto-mocked "real" type>). But here we face two problems:

- How to extend the behavior of standard PHPUnit mock generator?
- How to detect "real" type of a function?

**Comment by kelunik** [comment]
Promises will be much less common in Amp v3, so it's hopefully no longer that relevant then.
