### ISSUE TITLE
Uncaught exception in a test method hangs it

### ISSUE THREAD

**Issue by dangoodman** [amphp/phpunit-util#8]
Shoulnd't it abort the loop instead? 

Same happens if we just remove the line `throw new Exception("TEST");`, but I'm not sure whether it's so by design.

```php
class MyAsyncTestCase extends AsyncTestCase
{
    function test()
    {
        Loop::repeat(1000, static function() { echo "alive\n"; });
        throw new Exception("TEST"); // Doesn't abort the loop. This method runs forever.
    }
}
```

**Comment by trowski** [comment]
I created a PR addressing this issue: #9. This issue exists because we don't want to make any assumptions about how long the loop needs to run for a test, but in the case of an exception being thrown from the test case, it's probably safe to assume the loop should not continue to run.

**Comment by dangoodman** [comment]
Got it. Thanks,
